RecipeViewerEvents.removeEntries('item', e => {
    e.remove("avaritia:infinity_catalyst")
    e.remove("avaritia:infinity_singularity")
    e.remove("avaritia:netherite_singularity")
    e.remove("avaritia:amethyst_singularity")
    e.remove("avaritia:emerald_singularity")
    e.remove("avaritia:diamond_singularity")
    e.remove("avaritia:quartz_singularity")
    e.remove("avaritia:redstone_singularity")
    e.remove("avaritia:lapis_singularity")
    e.remove("avaritia:gold_singularity")
    e.remove("avaritia:iron_singularity")
    e.remove("avaritia:copper_singularity")
    e.remove("avaritia:compressed_crafting_table" )
    e.remove("avaritia:double_compressed_crafting_table" )
    e.remove("avaritia:extreme_crafting_table" )
    e.remove("avaritia:diamond_lattice" )
    e.remove("avaritia:crystal_matrix_ingot" )
    e.remove("avaritia:crystal_matrix_block" )
    e.remove("avaritia:compressor" )
    e.remove("avaritia:neutron_collector" )
    e.remove("avaritia:infinity_chest")
    e.remove("avaritia:json_singularity")
    e.remove("avaritia:record_fragment")
})

RecipeViewerEvents.removeRecipes(e => {
    e.remove("avaritia:/collector")
})