RecipeViewerEvents.removeEntries('item', e => {
//     e.remove('oritech:plastic_sheet')
//     e.remove('oritech:silicon')
    e.remove('oritech:raw_silicon')
//     e.remove('oritech:silicon_wafer')
//     e.remove('oritech:motor')
//     e.remove('oritech:basic_battery')
//     e.remove('oritech:advanced_battery')
//     e.remove('oritech:magnetic_coil')
//     e.remove('oritech:biosteel_block')
//     e.remove('oritech:biosteel_ingot')
//     e.remove('oritech:biosteel_dust')
//     e.remove('oritech:silicon_block')
//     e.remove('oritech:quartz_dust')
    e.remove("oritech:uranium_dust_block")
    e.remove("oritech:biosteel_block")
    e.remove("oritech:biosteel_dust")
    e.remove("oritech:biomass_block")
    e.remove("oritech:silicon_block")

    e.remove("oritech:deepslate_platinum_ore")
    e.remove("oritech:resource_node_platinum")
    e.remove("oritech:resource_node_redstone")
    e.remove("oritech:resource_node_lapis")
    e.remove("oritech:resource_node_iron")
    e.remove("oritech:resource_node_coal")
    e.remove("oritech:resource_node_gold")
    e.remove("oritech:resource_node_emerald")
    e.remove("oritech:resource_node_diamond")
    e.remove("oritech:resource_node_copper")
    e.remove("oritech:resource_node_uranium")
})