// RecipeViewerEvents.removeEntries('item', e => {
//     e.remove('oritech:plastic_sheet')
//     e.remove('oritech:silicon')
//     e.remove('oritech:raw_silicon')
//     e.remove('oritech:silicon_wafer')
//     e.remove('oritech:motor')
//     e.remove('oritech:basic_battery')
//     e.remove('oritech:advanced_battery')
//     e.remove('oritech:magnetic_coil')
//     e.remove('oritech:biosteel_block')
//     e.remove('oritech:biosteel_ingot')
//     e.remove('oritech:biosteel_dust')
//     e.remove('oritech:silicon_block')
//     e.remove('oritech:quartz_dust')
// })