 RecipeViewerEvents.removeEntries('item', e => {
    e.remove('railcraft:bushing_gear')
    e.remove('railcraft:coal_coke')
    e.remove('railcraft:coal_coke_block')
    e.remove('railcraft:coke_oven_bricks')
    e.remove('railcraft:silver_ore')
    e.remove('railcraft:deepslate_silver_ore')
    e.remove('railcraft:sulfur_ore')
    e.remove('railcraft:deepslate_sulfur_ore')
    e.remove('railcraft:coal_dust')
    e.remove('railcraft:charcoal_dust')
    e.remove('railcraft:ender_dust')
    e.remove('railcraft:raw_firestone')
    e.remove('railcraft:cut_firestone')
    e.remove('railcraft:refined_firestone')
    e.remove('railcraft:cracked_firestone')
    e.remove('railcraft:saltpeter_ore')
})