name = "Moons Pack"
author = "jmcmoon"
version = "1.0.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8888f8e77696cd00b744f54a3e4edfecec62d9e37eb47f2c126b042741c80328"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"

[options]
acceptable-game-versions = ["1.21"]
