name = "Moons Pack"
author = "jmcmoon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a48b022b98eaec8bb6d86013a7a5a210f9e9fff4922193921cc86281890110c7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"

[options]
acceptable-game-versions = ["1.21"]
