name = "Moons Pack"
author = "jmcmoon"
version = "1.0.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "033136f2f02b444e8b89f9a85db9130ff9c5b4a71008d7dc1d660dd5413be067"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"

[options]
acceptable-game-versions = ["1.21"]
