MMREvents.machines(e => {
    e.create("mmr:neutron_extractor")
        .name("Neutron Extractor")
        .color("#FF292938")
        .structure(
            MMRStructureBuilder.create()
                .pattern([
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                 sss                 ",
                        "               sssssss               ",
                        "               sssssss               ",
                        "              sssssssss              ",
                        "              sssssssss              ",
                        "              sssssssss              ",
                        "               sssssss               ",
                        "               sssssss               ",
                        "                 sss                 ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                sssss                ",
                        "              sssssssss              ",
                        "             sssssssssss             ",
                        "            sssssiiisssss            ",
                        "            sssiiiiiiisss            ",
                        "           ssssiiiiiiissss           ",
                        "           sssiiiiiiiiisss           ",
                        "           sssiiiiiiiiisss           ",
                        "           sssiiiiiiiiisss           ",
                        "           ssssiiiiiiissss           ",
                        "            sssiiiiiiisss            ",
                        "            sssssiiisssss            ",
                        "             sssssssssss             ",
                        "              sssssssss              ",
                        "                sssss                ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                sssss                ",
                        "              sssssssss              ",
                        "            ssssiiiiissss            ",
                        "           sssiiiiiiiiisss           ",
                        "           ssiiiiiiiiiiiss           ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "           ssiiiiiiiiiiiss           ",
                        "           sssiiiiiiiiisss           ",
                        "            ssssiiiiissss            ",
                        "              sssssssss              ",
                        "                sssss                ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "              sssssssss              ",
                        "            ssssiiiiissss            ",
                        "           sssiiiiiiiiisss           ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "           sssiiiiiiiiisss           ",
                        "            ssssiiiiissss            ",
                        "              sssssssss              ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                 sss                 ",
                        "             sssssssssss             ",
                        "            ssiiiiiiiiiss            ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      ssiiiiiiiiiiiiiiiiiiiiiss      ",
                        "      ssiiiiiiiiiiiiiiiiiiiiiss      ",
                        "      ssiiiiiiiiiiiiiiiiiiiiiss      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "            ssiiiiiiiiiss            ",
                        "             sssssssssss             ",
                        "                 sss                 ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                sssss                ",
                        "             ssssiiissss             ",
                        "           ssiiiiiiiiiiiss           ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     ssiiiiiiiiiiiiiiiiiiiiiiiss     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     ssiiiiiiiiiiiiiiiiiiiiiiiss     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "           ssiiiiiiiiiiiss           ",
                        "             ssssiiissss             ",
                        "                sssss                ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                 sss                 ",
                        "             ssssiiissss             ",
                        "           ssiiiiiiiiiiiss           ",
                        "          siiiiiiiiiiiiiiis          ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "          siiiiiiiiiiiiiiis          ",
                        "           ssiiiiiiiiiiiss           ",
                        "             ssssiiissss             ",
                        "                 sss                 ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "             sssssssssss             ",
                        "           ssiiiiiiiiiiiss           ",
                        "          siiiiiiiiiiiiiiis          ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "          siiiiiiiiiiiiiiis          ",
                        "           ssiiiiiiiiiiiss           ",
                        "             sssssssssss             ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "              sssssssss              ",
                        "            ssiiiiiiiiiss            ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "   siiiiiiiiiiiii   iiiiiiiiiiiiis   ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "   siiiiiiiiiiiii   iiiiiiiiiiiiis   ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "            ssiiiiiiiiiss            ",
                        "              sssssssss              ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                sssss                ",
                        "            ssssiiiiissss            ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "            ssssiiiiissss            ",
                        "                sssss                ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "              sssssssss              ",
                        "           sssiiiiiiiiisss           ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "           sssiiiiiiiiisss           ",
                        "              sssssssss              ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                sssss                ",
                        "            ssssiiiiissss            ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiii               iiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiii               iiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "            ssssiiiiissss            ",
                        "                sssss                ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "              sssssssss              ",
                        "           sssiiiiiiiiisss           ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiii               iiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiii               iiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "           sssiiiiiiiiisss           ",
                        "              sssssssss              ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "             sssssssssss             ",
                        "           ssiiiiiiiiiiiss           ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiii               iiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiii               iiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "           ssiiiiiiiiiiiss           ",
                        "             sssssssssss             ",
                        "                                     "
                    ],
                    [
                        "                 sss                 ",
                        "            ssppsiiisppss            ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "            sssssiiisssss            ",
                        "                 sss                 "
                    ],
                    [
                        "               ss   ss               ",
                        "            sssii   iisss            ",
                        "          ssiiiii i iiiiiss          ",
                        "        ssiiiiiii   iiiiiiiss        ",
                        "       siiiiiiiii   iiiiiiiiis       ",
                        "      siiiiiiiiii   iiiiiiiiiis      ",
                        "     siiiiiiiiiii   iiiiiiiiiiis     ",
                        "    siiiiiiiiiiii   iiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiii   iiiiiiiiiiiiis   ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiii               iiiiiiiis  ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        "  siiiiiiii               iiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "   siiiiiiiiiiiii   iiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "            sssiiiiiiisss            ",
                        "               sssssss               "
                    ],
                    [
                        "               s     s               ",
                        "           ssssi     issss           ",
                        "         ssiiiii  i  iiiiiss         ",
                        "        siiiiiii     iiiiiiis        ",
                        "       siiiiiiii     iiiiiiiis       ",
                        "     ssiiiiiiiii     iiiiiiiiiss     ",
                        "     siiiiiiiiii     iiiiiiiiiis     ",
                        "    siiiiiiiiiii     iiiiiiiiiiis    ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     ssiiiiiiiiiiiiiiiiiiiiiiiss     ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "           ssssiiiiiiissss           ",
                        "               sssssss               "
                    ],
                    [
                        "              s       s              ",
                        "           sssi       isss           ",
                        "         ssiiii   i   iiiiss         ",
                        "        siiiiii       iiiiiis        ",
                        "      ssiiiiiii       iiiiiiiss      ",
                        "     siiiiiiiii       iiiiiiiiis     ",
                        "    siiiiiiiiii       iiiiiiiiiis    ",
                        "    siiiiiiiiii       iiiiiiiiiis    ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      ssiiiiiiiiiiiiiiiiiiiiiss      ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "           sssiiiiiiiiisss           ",
                        "              ssspppsss              "
                    ],
                    [
                        "              s       s              ",
                        "           sssi       isss           ",
                        "         ssiiii   m   iiiiss         ",
                        "        siiiiii       iiiiiis        ",
                        "      ssiiiiiii       iiiiiiiss      ",
                        "     siiiiiiiii       iiiiiiiiis     ",
                        "    siiiiiiiiii       iiiiiiiiiis    ",
                        "    siiiiiiiiii       iiiiiiiiiis    ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii          b          iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      ssiiiiiiiiiiiiiiiiiiiiiss      ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "           sssiiiiiiiiisss           ",
                        "              sssssssss              "
                    ],
                    [
                        "              s       s              ",
                        "           sssi       isss           ",
                        "         ssiiii       iiiiss         ",
                        "        siiiiii       iiiiiis        ",
                        "      ssiiiiiii       iiiiiiiss      ",
                        "     siiiiiiiii       iiiiiiiiis     ",
                        "    siiiiiiiiii       iiiiiiiiiis    ",
                        "    siiiiiiiiii       iiiiiiiiiis    ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      ssiiiiiiiiiiiiiiiiiiiiiss      ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "           sssiiiiiiiiisss           ",
                        "              ssspppsss              "
                    ],
                    [
                        "               s     s               ",
                        "           ssssi     issss           ",
                        "         ssiiiii     iiiiiss         ",
                        "        siiiiiii     iiiiiiis        ",
                        "       siiiiiiii     iiiiiiiis       ",
                        "     ssiiiiiiiii     iiiiiiiiiss     ",
                        "     siiiiiiiiii     iiiiiiiiiis     ",
                        "    siiiiiiiiiii     iiiiiiiiiiis    ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     ssiiiiiiiiiiiiiiiiiiiiiiiss     ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "           ssssiiiiiiissss           ",
                        "               sssssss               "
                    ],
                    [
                        "               ss   ss               ",
                        "            sssii   iisss            ",
                        "          ssiiiii   iiiiiss          ",
                        "        ssiiiiiii   iiiiiiiss        ",
                        "       siiiiiiiii   iiiiiiiiis       ",
                        "      siiiiiiiiii   iiiiiiiiiis      ",
                        "     siiiiiiiiiii   iiiiiiiiiiis     ",
                        "    siiiiiiiiiiii   iiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiii   iiiiiiiiiiiiis   ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiii               iiiiiiiis  ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiii                     iiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        "  siiiiiiii               iiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "   siiiiiiiiiiiii   iiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "            sssiiiiiiisss            ",
                        "               sssssss               "
                    ],
                    [
                        "                 sss                 ",
                        "            sssssiiisssss            ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        "siiiiiiii                   iiiiiiiis",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "            sssssiiisssss            ",
                        "                 sss                 "
                    ],
                    [
                        "                                     ",
                        "             sssssssssss             ",
                        "           ssiiiiiiiiiiiss           ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiii               iiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiii                   iiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiii               iiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "           ssiiiiiiiiiiiss           ",
                        "             sssssssssss             ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "              sssssssss              ",
                        "           sssiiiiiiiiisss           ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiii               iiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiii                 iiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiii               iiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "           sssiiiiiiiiisss           ",
                        "              sssssssss              ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                sssss                ",
                        "            ssssiiiiissss            ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiii               iiiiiiiis  ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        " siiiiiiiii               iiiiiiiiis ",
                        "  siiiiiiii               iiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "            ssssiiiiissss            ",
                        "                sssss                ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "              sssssssss              ",
                        "           sssiiiiiiiiisss           ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiii             iiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "           sssiiiiiiiiisss           ",
                        "              sssssssss              ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                sssss                ",
                        "            ssssiiiiissss            ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "  siiiiiiiiii           iiiiiiiiiis  ",
                        "   siiiiiiiiii         iiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "            ssssiiiiissss            ",
                        "                sssss                ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "              sssssssss              ",
                        "            ssiiiiiiiiiss            ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "   siiiiiiiiiiiii   iiiiiiiiiiiiis   ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiii       iiiiiiiiiiis   ",
                        "   siiiiiiiiiiii     iiiiiiiiiiiis   ",
                        "   siiiiiiiiiiiii   iiiiiiiiiiiiis   ",
                        "   siiiiiiiiiiiiiiiiiiiiiiiiiiiiis   ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "            ssiiiiiiiiiss            ",
                        "              sssssssss              ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "             sssssssssss             ",
                        "           ssiiiiiiiiiiiss           ",
                        "          siiiiiiiiiiiiiiis          ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "          siiiiiiiiiiiiiiis          ",
                        "           ssiiiiiiiiiiiss           ",
                        "             sssssssssss             ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                 sss                 ",
                        "             ssssiiissss             ",
                        "           ssiiiiiiiiiiiss           ",
                        "          siiiiiiiiiiiiiiis          ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "    siiiiiiiiiiiiiiiiiiiiiiiiiiis    ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "          siiiiiiiiiiiiiiis          ",
                        "           ssiiiiiiiiiiiss           ",
                        "             ssssiiissss             ",
                        "                 sss                 ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                sssss                ",
                        "             ssssiiissss             ",
                        "           ssiiiiiiiiiiiss           ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "     ssiiiiiiiiiiiiiiiiiiiiiiiss     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     siiiiiiiiiiiiiiiiiiiiiiiiis     ",
                        "     ssiiiiiiiiiiiiiiiiiiiiiiiss     ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "      siiiiiiiiiiiiiiiiiiiiiiis      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "           ssiiiiiiiiiiiss           ",
                        "             ssssiiissss             ",
                        "                sssss                ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                 sss                 ",
                        "             sssssssssss             ",
                        "            ssiiiiiiiiiss            ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "      ssiiiiiiiiiiiiiiiiiiiiiss      ",
                        "      ssiiiiiiiiiiiiiiiiiiiiiss      ",
                        "      ssiiiiiiiiiiiiiiiiiiiiiss      ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       siiiiiiiiiiiiiiiiiiiiis       ",
                        "       ssiiiiiiiiiiiiiiiiiiiss       ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "         siiiiiiiiiiiiiiiiis         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "            ssiiiiiiiiiss            ",
                        "             sssssssssss             ",
                        "                 sss                 ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "              sssssssss              ",
                        "            ssssiiiiissss            ",
                        "           sssiiiiiiiiisss           ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "        siiiiiiiiiiiiiiiiiiis        ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "        ssiiiiiiiiiiiiiiiiiss        ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "           sssiiiiiiiiisss           ",
                        "            ssssiiiiissss            ",
                        "              sssssssss              ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                sssss                ",
                        "              sssssssss              ",
                        "            ssssiiiiissss            ",
                        "           sssiiiiiiiiisss           ",
                        "           ssiiiiiiiiiiiss           ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "         ssiiiiiiiiiiiiiiiss         ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "          ssiiiiiiiiiiiiiss          ",
                        "           ssiiiiiiiiiiiss           ",
                        "           sssiiiiiiiiisss           ",
                        "            ssssiiiiissss            ",
                        "              sssssssss              ",
                        "                sssss                ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                sssss                ",
                        "              sssssssss              ",
                        "             sssssssssss             ",
                        "            sssssiiisssss            ",
                        "            sssiiiiiiisss            ",
                        "           ssssiiiiiiissss           ",
                        "           sssiiiiiiiiisss           ",
                        "           sssiiiiiiiiisss           ",
                        "           sssiiiiiiiiisss           ",
                        "           ssssiiiiiiissss           ",
                        "            sssiiiiiiisss            ",
                        "            sssssiiisssss            ",
                        "             sssssssssss             ",
                        "              sssssssss              ",
                        "                sssss                ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ],
                    [
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                 sss                 ",
                        "               sssssss               ",
                        "               sssssss               ",
                        "              sssssssss              ",
                        "              sssssssss              ",
                        "              sssssssss              ",
                        "               sssssss               ",
                        "               sssssss               ",
                        "                 sss                 ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     ",
                        "                                     "
                    ]
                ])
                .keys({
                    "p": [
                        "#modular_machinery_reborn:energyinputhatch",
                        "#modular_machinery_reborn:fluidinputhatch",
                        "#modular_machinery_reborn:outputbus",
                        "modular_machinery_reborn:casing_plain"
                    ],
                    "s": "modular_machinery_reborn:casing_plain",
                    "i": "modular_machinery_reborn:casing_plain",
                    "b": "oritech:black_hole_block"
                })
        )
})

ServerEvents.recipes(event => {
  event.recipes.modular_machinery_reborn
    .machine_recipe("mmr:neutron_extractor", 7200)
    .requireEnergyPerTick(320000, 16, 16)
    .produceItem("1x avaritia:neutron_pile", 96, 32)
    .dimensions([
        "ae2:spatial_storage",
        "dimdoors:personal_pockets",
        "dimdoors:public_pockets",
        "dimdoors:dungeon_pockets"
    ], true)
    .width(128)
    .height(128)
    .progressData(
        ProgressData.create()
            .x(56)
            .y(32)
            .direction('left')
    )
})