MMREvents.machines(e => {
    e.create("mmr:resonating_combinator")
        .name("Resonating Combinator")
        .color("#FF052a32")
        .structure(
            MMRStructureBuilder.create()
                .pattern([
                  [
                    "ccccccccc",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "ccccccccc",
                  ],
                  [
                    "ccccccccc",
                    "   ccc   ",
                    "   ccc   ",
                    "    c    ",
                    "    c    ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "    c    ",
                    "    c    ",
                    "   ccc   ",
                    "   ccc   ",
                    "ccccccccc",
                  ],
                  [
                    "ccccccccc",
                    "  ccccc  ",
                    "  ccccc  ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "    c    ",
                    "    c    ",
                    "    c    ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "    c    ",
                    "    c    ",
                    "    c    ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "ccccccccc",
                  ],
                  [
                    "ccccccccc",
                    " ccccccc ",
                    " ccccccc ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "    c    ",
                    "    c    ",
                    "    c    ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "    c    ",
                    "    c    ",
                    "    c    ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "  ccccc  ",
                    " ccccccc ",
                    " ccccccc ",
                    "cccpppccc",
                  ],
                  [
                    "ccccmcccc",
                    " cctgtcc ",
                    " cctgtcc ",
                    " cctgtcc ",
                    " cctgtcc ",
                    "  ctgtc  ",
                    "  ctgtc  ",
                    "  ctgtc  ",
                    "  ctgtc  ",
                    "  ctgtc  ",
                    "  ctgtc  ",
                    "   tgt   ",
                    "   tgt   ",
                    "   tgt   ",
                    "   tgt   ",
                    "   tgt   ",
                    "   cgc   ",
                    "    g    ",
                    "    g    ",
                    "    g    ",
                    "    g    ",
                    "    g    ",
                    "    g    ",
                    "    g    ",
                    "   cgc   ",
                    "   tgt   ",
                    "   tgt   ",
                    "   tgt   ",
                    "   tgt   ",
                    "   tgt   ",
                    "  ctgtc  ",
                    "  ctgtc  ",
                    "  ctgtc  ",
                    "  ctgtc  ",
                    "  ctgtc  ",
                    "  ctgtc  ",
                    " cctgtcc ",
                    " cctgtcc ",
                    " cctgtcc ",
                    " cctgtcc ",
                    "cccpppccc",
                  ],
                  [
                    "ccccccccc",
                    " ccccccc ",
                    " ccccccc ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "    c    ",
                    "    c    ",
                    "    c    ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "    c    ",
                    "    c    ",
                    "    c    ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "  ccccc  ",
                    " ccccccc ",
                    " ccccccc ",
                    "cccpppccc",
                  ],
                  [
                    "ccccccccc",
                    "  ccccc  ",
                    "  ccccc  ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "    c    ",
                    "    c    ",
                    "    c    ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "    c    ",
                    "    c    ",
                    "    c    ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "   ccc   ",
                    "  ccccc  ",
                    "  ccccc  ",
                    "ccccccccc",
                  ],
                  [
                    "ccccccccc",
                    "   ccc   ",
                    "   ccc   ",
                    "    c    ",
                    "    c    ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "    c    ",
                    "    c    ",
                    "   ccc   ",
                    "   ccc   ",
                    "ccccccccc",
                  ],
                  [
                    "ccccccccc",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "         ",
                    "ccccccccc",
                  ],
                ]
              )
              .keys({
                    "p": [
                        "#modular_machinery_reborn:energyinputhatch",
                        "#modular_machinery_reborn:inputbus",
                        "#modular_machinery_reborn:outputbus",
                        "modular_machinery_reborn:casing_plain"
                    ],
                    "c": "modular_machinery_reborn:casing_plain",
                    "t": "modern_industrialization:superconductor_coil",
                    "g": "ae2:quartz_vibrant_glass"
                })
        )
})

ServerEvents.recipes(event => {
  event.recipes.modular_machinery_reborn
    .machine_recipe("mmr:resonating_combinator", 7200)
    .requireEnergyPerTick(80000, 8, 10)
    .requireItem("64x dimdoors:clod", 32, 8)
    .requireItem("8x deeperdarker:resonarium", 32, 28)
    .requireItem("1x enderitemod:enderite_ingot", 32, 48)
    .produceItem("1x replication:raw_replica", 84, 28)
    .dimensions([
        "deeperdarker:otherside"
    ], false)
    .width(108)
    .height(72)
    .progressData(
        ProgressData.create()
            .x(56)
            .y(28)
            .direction('left')
    )
})