[creativeModeTabs]
enableCreativeModeTabs = true
syncSelectedCreativeModeTab = false

[stackGroups]
enableStackGroups = true
disabledStackGroups = [
    "minecraft:shovels",
    "minecraft:pickaxes",
    "minecraft:axes",
    "minecraft:head_armor",
    "minecraft:hoes",
    "minecraft:swords",
    "minecraft:chest_armor",
    "minecraft:leg_armor",
    "minecraft:foot_armor",
    "c:foods",
    "minecraft:rails",
    "minecraft:minecarts",
    "minecraft:flowers"
]
