name: Automatic Versioning

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  build-version:
    runs-on: ubuntu-latest
    outputs:
        TAG: ${{ steps.convver-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set Credentials
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: |
          npm set "//npm.pkg.github.com/:_authToken" ${{ secrets.GITHUB_TOKEN }}
          npm install -g @jmcmahon1999/convver --@jmcmahon1999:registry=https://npm.pkg.github.com/
          npm install -g @jmcmahon1999/convver-packwiz --@jmcmahon1999:registry=https://npm.pkg.github.com/
      - name: Convver Update
        id: convver-update
        run: convver update packwiz -q -p ${{ github.ref_name }}
      - name: Get New Version
        id: convver-version
        run: echo "tag=$( convver current packwiz)" >> $GITHUB_OUTPUT
      - name: Push Changes
        if: steps.convver-update.outcome == 'success'
        run: git push --follow-tags
      - uses: actions/setup-go@v6
        if: steps.convver-update.outcome == 'success'
        with:
          go-version: 1.23
      - name: Install packwiz
        if: steps.convver-update.outcome == 'success'
        run: go install github.com/packwiz/packwiz@latest
      - name: Build Modpack Distributions
        if: steps.convver-update.outcome == 'success'
        run: ./build/build.sh
      - name: Archive Built Wheels
        id: archive-wheel
        if: steps.convver-update.outcome == 'success'
        uses: actions/upload-artifact@v5
        with:
          name: build-$TAG
          path: ./build/dist/*